services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      PUID: '1004'
      PGID: '131'
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./data:/data
        - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
        - 9000:9000
    networks:
      proxy:  # null
        ipv4_address: 172.40.0.4
    dns:
       - 1.1.1.1
    restart: unless-stopped

networks:
  proxy:
    external: true
