version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    env_file:
      - ../../secrets.env
    container_name: yoURLs
    networks:
      proxy:
        ipv4_address: 172.40.0.10
      default:
#      - proxy
#      - default
    dns:
#      - 172.40.0.3
      - 8.8.8.8
      - 1.1.1.1
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.link-secure.entrypoints: websecure
      traefik.http.routers.link-secure.middlewares: default@file
      traefik.http.routers.link-secure.rule: Host(`link.${DOMAIN}`)
      traefik.http.routers.link-secure.service: link
      traefik.http.routers.link-secure.tls: "true"
      traefik.http.routers.link-secure.tls.certresolver: http_resolver
      traefik.http.routers.link.entrypoints: web
      traefik.http.routers.link.rule: Host(`link.${DOMAIN}`)
      traefik.http.services.link.loadbalancer.server.port: "80"

  yourls-db:
    image: mysql
    restart: always
    networks:
      default:
    env_file: env.mysql
    volumes:
#      - ./mysql_yourls_db:/var/lib/mysql
      - ./data:/var/lib/mysql
networks:
  proxy:
    external: true
